### ISSUE TITLE
getPosts with dioClient vs restClient

### ISSUE THREAD

**Issue by gc-robotics** [zubairehman/flutter-boilerplate-project#102]
Get_posts.dart is implemented using _dioClient, but it has a commented section that shows an implementation based on _restClient. 

When to use one or the other? 

thanks.

**Comment by zubairehman** [comment]
Hi @gc-robotics,

You can use either one of the provided clients, the **rest_client** implementation is commented on because it's just to give an idea on how to make a network call using the **rest_client**.

Thanks.
