### ISSUE TITLE
Null Safety Migration

### ISSUE THREAD

**Issue by hemantsavkar** [zubairehman/flutter-boilerplate-project#105]
After Migrating To Null Safety Getting Below Errors While Running

                                                                     ^  
lib/di/components/app_component.inject.dart:86:30: Error: Field '_singletonSharedPreferenceHelper' should be initialized because its type 'SharedPreferenceHelper' doesn't allow null.
 - 'SharedPreferenceHelper' is from 'package:myapp/data/sharedpref/shared_preference_helper.dart' ('lib/data/sharedpref/shared_preference_helper.dart').
  _i3.SharedPreferenceHelper _singletonSharedPreferenceHelper;          
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^           
lib/di/components/app_component.inject.dart:88:28: Error: Field '_singletonPreferenceRepository' should be initialized because its type 'PreferenceRepository' doesn't allow null.
 - 'PreferenceRepository' is from 'package:myapp//data/sharedpref/preferencerepository.dart' ('lib/data/sharedpref/preferencerepository.dart').
  _i4.PreferenceRepository _singletonPreferenceRepository;              
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^               
lib/di/components/app_component.inject.dart:92:11: Error: Field '_singletonDio' should be initialized because its type 'Dio' doesn't allow null.
 - 'Dio' is from 'package:dio/src/dio.dart' ('/Users/hemantsavkar/.pub-cache/hosted/pub.dartlang.org/dio-4.0.0/lib/src/dio.dart').
  _i6.Dio _singletonDio;                                                
          ^^^^^^^^^^^^^                                                 
lib/di/components/app_component.inject.dart:94:17: Error: Field '_singletonDioClient' should be initialized because its type 'DioClient' doesn't allow null.
 - 'DioClient' is from 'package:myapp/data/network/dio_client.dart' ('lib/data/network/dio_client.dart').
  _i7.DioClient _singletonDioClient;

**Comment by zubairehman** [comment]
Hi @hemantsavkar,

I have implemented DI using **get_it** and the above errors should be resolved. Please feel free to open this issue if you are still facing any issues.

Thanks.
