### ISSUE TITLE
Actual use of Provider

### ISSUE THREAD

**Issue by benforsrup** [zubairehman/flutter-boilerplate-project#11]
Hey,

I don't see an actual use of the Provider package in any of the files. Perhaps you could add a basic example of combining provider with mobx?

**Comment by zubairehman** [comment]
Hi, i will surely add an example of provider with some other features really soon :)

**Comment by zubairehman** [comment]
@benforsrup Please have a look at the latest implementation of `main.dart`. Please let me know if you still need other example.
