### ISSUE TITLE
Why should use both Mobx and Provider for State management?

### ISSUE THREAD

**Issue by MrGru** [zubairehman/flutter-boilerplate-project#111]
I see that Provider is enough for state management. Why do we need both Provider and Mobx?

**Comment by zubairehman** [comment]
Hi @MrGru  ,

Thanks for pointing it out. Please follow this branch for upcoming changes: https://github.com/zubairehman/flutter-boilerplate-project/tree/feature/mvi. The provider has been removed as I was just using it for providing stores to widgets.

Thanks
