### ISSUE TITLE
Replace provider by get_it

### ISSUE THREAD

**Issue by quanghd96** [zubairehman/flutter-boilerplate-project#113]
I see get_it can be used instead of Provider. So why you use both it?

// in service_locator.dart 
getIt.registerSingleton(ThemeStore(getIt<Repository>()));

// my_app.dart
Provider<ThemeStore>(create: (_) => _themeStore),

I think we only need to use ThemeStore by get_it or provider. Not need both

**Comment by dyardy** [comment]
This is similar to https://github.com/zubairehman/flutter-boilerplate-project/issues/118

I understand using Provider to get from singleton (getIt) in one location and making it available in different locations in the tree/hierarchy however I do not see the reason for new-ing it up as found in my_app.dart
`final PostStore _postStore = PostStore(getIt<Repository>());`

when you may just get from getIt via
`final PostStore _postStore = getIt<PostStore>();`

**Comment by zubairehman** [comment]
Hi @dyardy,

Thanks for pointing it out. Please follow this branch for upcoming changes: https://github.com/zubairehman/flutter-boilerplate-project/tree/feature/mvi

I will make sure to merge the DI-related changes in the master branch as well. Let me know if you have any comments.

Thanks
