### ISSUE TITLE
CommonRespository get error

### ISSUE THREAD

**Issue by fantasyrock2020** [zubairehman/flutter-boilerplate-project#120]
I'm getting error in IOS (Android build success)
<img width="802" alt="Screen Shot 2022-02-11 at 09 38 06" src="https://user-images.githubusercontent.com/26890501/153529483-88ed7958-79ec-4d90-898f-b2a8f855fd83.png">

Here my service_locator
<img width="604" alt="Screen Shot 2022-02-11 at 09 38 44" src="https://user-images.githubusercontent.com/26890501/153529524-f1a3321a-56ec-4bbb-9931-60267401e46f.png">

Here my_app
<img width="598" alt="Screen Shot 2022-02-11 at 09 39 19" src="https://user-images.githubusercontent.com/26890501/153529591-38fa6c53-b7b1-484d-9e0a-ee8037c65cc0.png">

Please help me

**Comment by zand-yasin** [comment]
@fantasyrock2020 

just remove Ios and Android folder and re initialise it, it reduced size app a lot for me, also it works for me for both.

you can do this following:
 
-Delete ios directory

**Comment by fantasyrock2020** [comment]
Thank @zand-yasin
I fixed it by change import link
