### ISSUE TITLE
URI target doesn't exist  

### ISSUE THREAD

**Issue by imsujan276** [zubairehman/flutter-boilerplate-project#16]
in the page app_component.dart, I can see an issue that is restricting from getting the app compiled. 

**import 'app_component.inject.dart' as g;**

but it is saying invalid URI target for **_app_component.inject.dart_**. What might be causing this issue?

**Comment by zubairehman** [comment]
Please check this issue
https://github.com/zubairehman/flutter-boilerplate-project/issues/15

**Comment by zubairehman** [comment]
Please check this issue
https://github.com/zubairehman/flutter-boilerplate-project/issues/15

**Comment by imsujan276** [comment]
thank you. I guess  I missed that :)
