### ISSUE TITLE
get_it is much  easier to user for dependancy injection

### ISSUE THREAD

**Issue by dhsont** [zubairehman/flutter-boilerplate-project#17]
Hi i like this boilerplate, 
 but creating  2 extra file of Class for dependency injection is unnecessary. 

we can use Get_it package which is easy to use and reduces unnecessary files.

https://pub.dev/packages/get_it @zubairehman @eladcandroid

**Comment by zubairehman** [comment]
@dhsont these extra files will be removed in the future release.
As get_it turned out to be a Service Locator (and I’m not a fan of this pattern), I decided to play with this library: inject.dart. It is heavily inspired by Dagger, that we normally use in Android, I’ve decided to dig into it.
