### ISSUE TITLE
The command in step 3 for code generation is slightly wrong.

### ISSUE THREAD

**Issue by Christian-Martensson** [zubairehman/flutter-boilerplate-project#19]
Hi! 
Noticed that the command for building the generated file is slightly wrong, it's missing two "-" for it to properly delete the conflicting outputs. This one works: 
flutter packages pub run build_runner watch --delete-conflicting-outputs
As opposed to the command in step 3 which doesn't successfuly delete the conflicting outputs (causing an error for me): 
flutter packages pub run build_runner build delete-conflicting-outputs

Hope it helps, thanks for starting this project!

**Comment by zubairehman** [comment]
@Christian-Martensson  Thanks for the correction, was a typo :)
