### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by ashishnimrot** [zubairehman/flutter-boilerplate-project#2]
Resolving dependencies...                                           9.2s

Compiler message:
file:///Users/ashish/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.6.0/lib/flushbar.dart:203:3: Error: Type 'FocusAttachment' not found.
  FocusAttachment _focusAttachment;
  ^^^^^^^^^^^^^^^
file:///Users/ashish/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.6.0/lib/flushbar.dart:203:3: Error: 'FocusAttachment' isn't a type.
  FocusAttachment _focusAttachment;
  ^^^^^^^^^^^^^^^
file:///Users/ashish/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.6.0/lib/flushbar.dart:224:35: Error: The method 'attach' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('file:///Users/ashish/Desktop/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'attach'.
    _focusAttachment = _focusNode.attach(context);
                                  ^^^^^^
file:///Users/ashish/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/flushbar-1.6.0/lib/flushbar.dart:235:16: Error: The method 'dispose' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('file:///Users/ashish/Desktop/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'dispose'.
    _focusNode.dispose();
               ^^^^^^^
Compiler failed on /Users/ashish/Desktop/And/f1/boilerplate/lib/main.dart
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        40.5s
Gradle task assembleDebug failed with exit code 1

**Comment by zubairehman** [comment]
try installing it like mentioned in the link: https://pub.dev/packages/flushbar#-installing-tab-

**Comment by ashishnimrot** [comment]
Sir same problem

**Comment by VergillR** [comment]
It sounds like you are still using flutter 1.5. To use flushbar 1.6.0, you need flutter 1.6.*, which you can get with `$ flutter channel beta`.
You can read the details in the [changelog](https://pub.dev/packages/flushbar#-changelog-tab-).

> 1.6.0 Breaking change. This fixes The method 'detach' isn't defined for the class 'FocusScopeNode' To use this version you will need Flutter 1.6, which in currently in the beta channel If you need to use Flutter Stable channel, stay in version 1.5.3 while flutter 1.6 is in beta.

**Comment by zubairehman** [comment]
@ashishnimrot try upgrading your flutter sdk and try again. Here is the link that will guide you how to upgrade flutter sdk: https://flutter.dev/docs/development/tools/sdk/upgrading

**Comment by zubairehman** [comment]
@ashishnimrot issue has been fixed, please check: https://github.com/zubairehman/flutter-boilerplate-project/commit/d274d3f9792760a8e58ab3826facaa2140198fcf

**Comment by dhsont** [comment]
You can use flushbar version  "1.5.3" 

this will solve issue.
