### ISSUE TITLE
analyzer dependency is in conflict

### ISSUE THREAD

**Issue by natanloterio** [zubairehman/flutter-boilerplate-project#23]
Hi, I just clonned the project, and tried get the dependencies. But got this error:

`[flutter-boilerplate-project] flutter packages get
Running "flutter pub get" in flutter-boilerplate-project...     
Because every version of inject_generator from git depends on analyzer ^0.34.0 and mobx_codegen >=0.1.3 depends on analyzer ^0.36.3, inject_generator from git is incompatible with mobx_codegen >=0.1.3.
So, because boilerplate depends on both mobx_codegen ^0.3.3+1 and inject_generator from git, version solving failed.
`

As you can see, inject_generator and mobx_codegen have different analyzer versions as dependencies.

Do you have any clue on how to solve this issue?

Thnks

**Comment by zubairehman** [comment]
@natanloterio have a look at this issue: https://github.com/zubairehman/flutter-boilerplate-project/issues/22
