### ISSUE TITLE
Provider and Mobx

### ISSUE THREAD

**Issue by dohoangnam1103** [zubairehman/flutter-boilerplate-project#26]
I am confused with using provider with mobx, can you add an example for it?

**Comment by zubairehman** [comment]
@dohoangnam1103 sure, i will add an example but for now please note that i am using provider just to pass stores to other widgets.

**Comment by dohoangnam1103** [comment]
> @dohoangnam1103 sure, i will add an example but for now please note that i am using provider just to pass stores to other widgets.

Yes. Currently I don't know how to use 1 store for 2 or more widgets. I want when changing the value in one widget, this change will appear in another widget. Can you give me an example of this?

**Comment by zubairehman** [comment]
@dohoangnam1103 please check the latest implementation of `theme_store.dart` and `main.dart`
let me know if you still need other examples.
