### ISSUE TITLE
Flutter 1.12.13?

### ISSUE THREAD

**Issue by blondie63** [zubairehman/flutter-boilerplate-project#28]
It works with last stable Flutter ?

**Comment by zubairehman** [comment]
Yes, It does.
Are you having any issues?

**Comment by blondie63** [comment]
yes, look:
<img width="1458" alt="zubairehman-log" src="https://user-images.githubusercontent.com/1261851/71554354-4f893900-2a1e-11ea-9784-a9e60fcea3e5.png">

**Comment by zubairehman** [comment]
I can see that you .g files are not properly generated. Please make sure you followed the steps mentioned here to clone and build the project:
https://github.com/zubairehman/flutter-boilerplate-project#how-to-use

**Comment by blondie63** [comment]
sorry I hadn't read carefully

**Comment by zubairehman** [comment]
no problem :)
i am gonna close this issue.
