### ISSUE TITLE
Kudos and Questions 

### ISSUE THREAD

**Issue by talamaska** [zubairehman/flutter-boilerplate-project#31]
That looks super good, I was trying mobx as well and Moor, I was wondering how it will look with the inject.dart. Thanks so much for this. There is only one thing that bothers me 
```
await future.then((postList) {
      this.postList = postList;
    }).catchError((error) {
      errorStore.errorMessage = DioErrorUtil.handleError(error);
    });
```
if it's in async function shouldn't you just return the future then catch chain and not await them?
If feels weird. I excpect awaits to be wrapped in try catch and not chain then and catch. like this 
```
try { 
this.postList = await _repository.getPosts();
} catch (e) {
errorStore.errorMessage = DioErrorUtil.handleError(error);
}
```

**Comment by zubairehman** [comment]
Hi, 
Thanks for your feedback.
Yes, you are right. The `await` keyword is un-necessary is this case. I have removed it and pushed the latest code.
