### ISSUE TITLE
Why use Mobx over RxDart or Provider

### ISSUE THREAD

**Issue by dhsont** [zubairehman/flutter-boilerplate-project#4]
A Beginners Question i am still confuse about streams.

As strems are supported with Provider package why we use Mobx or RxDart.

and which is better   Mobx or RxDart.

**Comment by zubairehman** [comment]
Hi,

Please look into the wiki for more details: [MobX vs RxDart](https://github.com/mobxjs/mobx/wiki/Mobx-vs-Reactive-Stream-Libraries-(RxJS,-Bacon,-etc))

Hope this helps :)
