### ISSUE TITLE
Why a central repository?

### ISSUE THREAD

**Issue by fcecchin** [zubairehman/flutter-boilerplate-project#45]
First of all, thank you @zubairehman and congrats for this awesome project.

I'd like to know why did you choose one central repository strategy? I guess this class will be huge if your domain has lots of domain classes. Why not one repo for each domain class?

Thank you again.

**Comment by zubairehman** [comment]
Hi @fcecchin,

Thanks for your feedback.
I totally agree with you that using a single repository is not a good idea when you have been working on a big project with many data sources. However, I have used a single repository to showcase how we can interact with different layers and pass data between them.

In a project with many data sources, you might use a **DataManager** holding reference of all the repositories as shown below:

**DataManager**

```
abstract class DataManager
    implements
        JobRepository,
        TaskRepository,
        ReceiptRepository,
        JobTaskReceiptRepository,
        TaskTemplatesRepository,
        UserRepository,
        NotificationsRepository,
        ConfigurationsRepository,
        DataRepository,
        ProblemRepository {}
```

**JobRepository**

```
abstract class JobRepository {
  Future<Tuple2<List<Job>, List<Problem>>> getJobs({List<int> jobIds});
  Future<bool> updateJob(Job job);
  Future<bool> clearAllJobs();
  Future<bool> removeJobs(List<int> jobIds);
  Future<SyncResult> syncAllJobs();
}
```

I hope this answers your question but feel free to ask if you have any questions.

**Comment by menglingyu** [comment]
why is implements,  not mixin ?
