### ISSUE TITLE
shared_preferences => localstorage

### ISSUE THREAD

**Issue by rodydavis** [zubairehman/flutter-boilerplate-project#5]
If you switch to local storage you can easily use this project on desktop: https://pub.dev/packages/localstorage

**Comment by AppleEducate** [comment]
shared_preferneces does not exist on the desktop yet. plus you could store the database this way too.

**Comment by zubairehman** [comment]
@AppleEducate thank you so much for your suggestion, i will definitely add support for the desktop in future releases :)

**Comment by AppleEducate** [comment]
Awesome! 😎

**Comment by max10rogerio** [comment]
Why do you not use Hive (https://docs.hivedb.dev/)?

**Comment by zubairehman** [comment]
Just a matter of choice. The overall ideas was to develop a boilerplate that helps reduce initial configuration. 

Thanks for sharing the link, i will take a look :)

**Comment by zubairehman** [comment]
shared preference now has support for web :)
