### ISSUE TITLE
Improvement of pubspec.yaml

### ISSUE THREAD

**Issue by ibrahimdevs** [zubairehman/flutter-boilerplate-project#51]
Hi Zubair,

Firstly, thank you for great work. 
I think some dependencies should moved to "dev_dependencies";
- flutter_launcher_icons
- mobx_codegen
Because they won't using in production, we need them only in development.

And I'm wondering why have you defined some dependencies in "dependency_overrides"? When I check it, they aren't defined regular dependencies section. Maybe, move them to "dependencies" will be better.

**Comment by zubairehman** [comment]
Hi @ibrahimdevs,

thanks for the suggestions.
some of the dependencies were in overrides coz of compatibility issues but I will update all the dependencies and push an update :)
