### ISSUE TITLE
how to remove dio from printing network logs

### ISSUE THREAD

**Issue by mrifni** [zubairehman/flutter-boilerplate-project#63]
how to remove dio from printing network logs

**Comment by zubairehman** [comment]
Hi @mrifni,

you can disable them from NetworkModule.dart, here is the link: https://github.com/zubairehman/flutter-boilerplate-project/blob/bb431e0a95b05f4fc1d2e066cdac67786ae8bcb6/lib/di/modules/netwok_module.dart#L32
