### ISSUE TITLE
exception when navigate to same page

### ISSUE THREAD

**Issue by davidchan666999** [zubairehman/flutter-boilerplate-project#65]
Hello, thank you for the great work first. I am trying your boilerplate and so far so good.
But i got one problem, when i call Navigator to same page, MobXCaughtException came out "setState() or markNeedsBuild() called during build.".

I just add a IconButton in home page
```IconButton(
        onPressed: () {
          Navigator.of(context).pushReplacementNamed(Routes.home);
        },
        icon: Icon(
          Icons.power_settings_new,
        ),
      ),
```
when i press it, exception occurred, how can i solve this problem, thanks.

**Comment by zubairehman** [comment]
@davidchan666999 Could you please explain a bit more on this and why do you want to navigate to the same page?

**Comment by zubairehman** [comment]
Please feel free to open it again if you are still facing the issue. Thanks
