### ISSUE TITLE
Add some more screens,repository, store data

### ISSUE THREAD

**Issue by Nagendrababu61** [zubairehman/flutter-boilerplate-project#67]
Hi, 
   Your base code is awesome. I was worked for 10 days. It's so hard to find add base repository, store, api register. After I added extra repository, store, api for my project. 
    I was struggling in store session. Please better to add multiple methods In repository, store and api consuming. It's easy to work some one using this template.
    Possible add network listeners, if network not available redirect to network page, unauthorised logout screen, unlimited scrolling with api. I am sure it's really great template for quick development for flutter app development.
    Once again, your project quick start is very good. 
    Kindly consider my request.
Thanks.

**Comment by kadnan0900** [comment]
@zubairehman Hi zubair i am also following this request. Please add Pagination in listview and also refresh token request in dio interceptor.

**Comment by zubairehman** [comment]
Hi @kadnan0900 ,

Thanks for pointing it out. Please follow this branch for upcoming changes: https://github.com/zubairehman/flutter-boilerplate-project/tree/feature/mvi. I have added interceptors in **Core** module, please have a look and let me know if you have any questions

Thanks
