### ISSUE TITLE
Infinite Loop when trying to build project

### ISSUE THREAD

**Issue by simsimatoo** [zubairehman/flutter-boilerplate-project#68]
Step 3:

This project uses inject library that works with code generation, execute the following command to generate files:

flutter packages pub run build_runner build --delete-conflicting-outputs
or watch command in order to keep the source code synced automatically:

flutter packages pub run build_runner watch

**Comment by teriansilva** [comment]
This step is never completing it seems. 

```
> flutter packages pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 370ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 11.6s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 998ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Deleting 3 declared outputs which already existed on disk.
[INFO] Checking for unexpected pre-existing outputs. completed, took 5ms

[INFO] Running build...
[INFO] inject_generator:inject_generator on test/widget_test.dart:Generating DI summary for boilerplate|test/widget_test.dart
[INFO] inject_generator:inject_generator on test/widget_test.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/app_theme.dart:Generating DI summary for boilerplate|lib/constants/app_theme.dart
[INFO] inject_generator:inject_generator on lib/constants/app_theme.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/assets.dart:Generating DI summary for boilerplate|lib/constants/assets.dart
[INFO] inject_generator:inject_generator on lib/constants/assets.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/colors.dart:Generating DI summary for boilerplate|lib/constants/colors.dart
[INFO] inject_generator:inject_generator on lib/constants/colors.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/dimens.dart:Generating DI summary for boilerplate|lib/constants/dimens.dart
[INFO] inject_generator:inject_generator on lib/constants/dimens.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/font_family.dart:Generating DI summary for boilerplate|lib/constants/font_family.dart
[INFO] inject_generator:inject_generator on lib/constants/font_family.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/strings.dart:Generating DI summary for boilerplate|lib/constants/strings.dart
[INFO] inject_generator:inject_generator on lib/constants/strings.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/local/constants/db_constants.dart:Generating DI summary for boilerplate|lib/data/local/constants/db_constants.dart
[INFO] inject_generator:inject_generator on lib/data/local/constants/db_constants.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/local/datasources/post/post_datasource.dart:Generating DI summary for boilerplate|lib/data/local/datasources/post/post_datasource.dart
[INFO] inject_generator:inject_generator on lib/data/local/datasources/post/post_datasource.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/network/apis/posts/post_api.dart:Generating DI summary for boilerplate|lib/data/network/apis/posts/post_api.dart
[INFO] inject_generator:inject_generator on lib/data/network/apis/posts/post_api.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/network/constants/endpoints.dart:Generating DI summary for boilerplate|lib/data/network/constants/endpoints.dart
[INFO] inject_generator:inject_generator on lib/data/network/constants/endpoints.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/network/dio_client.dart:Generating DI summary for boilerplate|lib/data/network/dio_client.dart
[INFO] inject_generator:inject_generator on lib/data/network/dio_client.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/network/exceptions/network_exceptions.dart:Generating DI summary for boilerplate|lib/data/network/exceptions/network_exceptions.dart
[INFO] inject_generator:inject_generator on lib/data/network/exceptions/network_exceptions.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/network/rest_client.dart:Generating DI summary for boilerplate|lib/data/network/rest_client.dart
[INFO] inject_generator:inject_generator on lib/data/network/rest_client.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/repository.dart:Generating DI summary for boilerplate|lib/data/repository.dart
[INFO] inject_generator:inject_generator on lib/data/repository.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/sharedpref/constants/preferences.dart:Generating DI summary for boilerplate|lib/data/sharedpref/constants/preferences.dart
[INFO] inject_generator:inject_generator on lib/data/sharedpref/constants/preferences.dart:After resolve
[INFO] Generating SDK summary...
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[INFO] inject_generator:inject_generator on lib/data/sharedpref/shared_preference_helper.dart:Generating DI summary for boilerplate|lib/data/sharedpref/shared_preference_helper.dart
[INFO] inject_generator:inject_generator on lib/data/sharedpref/shared_preference_helper.dart:After resolve
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[INFO] 2.5s elapsed, 1/17 actions completed.
[INFO] 3.6s elapsed, 1/17 actions completed.
[INFO] 4.6s elapsed, 1/17 actions completed.
[INFO] 5.6s elapsed, 1/17 actions completed.
[INFO] 6.7s elapsed, 1/17 actions completed.
[INFO] 7.8s elapsed, 1/17 actions completed.
[INFO] 8.9s elapsed, 1/17 actions completed.
[INFO] 10.0s elapsed, 1/17 actions completed.
[INFO] 11.0s elapsed, 1/17 actions completed.
[INFO] 12.0s elapsed, 1/17 actions completed.
[INFO] 13.1s elapsed, 1/17 actions completed.
[INFO] 14.2s elapsed, 1/17 actions completed.
[INFO] 15.2s elapsed, 1/17 actions completed.
[INFO] 16.3s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - inject_generator:inject_generator on lib/constants/app_theme.dart
  - inject_generator:inject_generator on lib/constants/assets.dart
  - inject_generator:inject_generator on lib/constants/colors.dart
  - inject_generator:inject_generator on lib/constants/dimens.dart
  - inject_generator:inject_generator on lib/constants/font_family.dart
  .. and 11 more

[INFO] 17.6s elapsed, 1/17 actions completed.
[INFO] 18.7s elapsed, 1/17 actions completed.
[INFO] 19.7s elapsed, 1/17 actions completed.
[INFO] 20.8s elapsed, 1/17 actions completed.
[INFO] 21.9s elapsed, 1/17 actions completed.
[INFO] 23.0s elapsed, 1/17 actions completed.
[INFO] 24.0s elapsed, 1/17 actions completed.
[INFO] 25.0s elapsed, 1/17 actions completed.
[INFO] 26.1s elapsed, 1/17 actions completed.
[INFO] 27.2s elapsed, 1/17 actions completed.
[INFO] 28.2s elapsed, 1/17 actions completed.
[INFO] 29.3s elapsed, 1/17 actions completed.
[INFO] 30.4s elapsed, 1/17 actions completed.
[INFO] 31.4s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - inject_generator:inject_generator on lib/constants/app_theme.dart
  - inject_generator:inject_generator on lib/constants/assets.dart
  - inject_generator:inject_generator on lib/constants/colors.dart
  - inject_generator:inject_generator on lib/constants/dimens.dart
  - inject_generator:inject_generator on lib/constants/font_family.dart
  .. and 11 more

[INFO] 32.7s elapsed, 1/17 actions completed.
[INFO] 33.8s elapsed, 1/17 actions completed.
[INFO] 34.9s elapsed, 1/17 actions completed.
[INFO] 36.0s elapsed, 1/17 actions completed.
[INFO] 37.1s elapsed, 1/17 actions completed.
[INFO] 38.1s elapsed, 1/17 actions completed.
[INFO] 39.2s elapsed, 1/17 actions completed.
[INFO] 40.3s elapsed, 1/17 actions completed.
[INFO] 41.4s elapsed, 1/17 actions completed.
[INFO] 42.5s elapsed, 1/17 actions completed.
[INFO] 43.6s elapsed, 1/17 actions completed.
[INFO] 44.7s elapsed, 1/17 actions completed.
[INFO] 45.7s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.0s, waiting on:
  - inject_generator:inject_generator on lib/constants/app_theme.dart
  - inject_generator:inject_generator on lib/constants/assets.dart
  - inject_generator:inject_generator on lib/constants/colors.dart
  - inject_generator:inject_generator on lib/constants/dimens.dart
  - inject_generator:inject_generator on lib/constants/font_family.dart
  .. and 11 more

[INFO] 47.7s elapsed, 1/17 actions completed.
[INFO] 48.8s elapsed, 1/17 actions completed.
[INFO] 49.9s elapsed, 1/17 actions completed.
[INFO] 51.0s elapsed, 1/17 actions completed.
[INFO] 52.0s elapsed, 1/17 actions completed.
[INFO] 53.0s elapsed, 1/17 actions completed.
[INFO] 54.1s elapsed, 1/17 actions completed.
```

**Comment by simsimatoo** [comment]
Thank you
________________________________
من: Marcus <notifications@github.com>
‏‏تم الإرسال: 19/ذو الحجة/1441 10:01 م
إلى: zubairehman/flutter-boilerplate-project <flutter-boilerplate-project@noreply.github.com>
نسخة: simsimatoo <al.alhamli@hotmail.com>; Author <author@noreply.github.com>
‏‏الموضوع: Re: [zubairehman/flutter-boilerplate-project] flutter-boilerplate-project (#68)


This step is never completing it seems.

> flutter packages pub run build_runner build --delete-conflicting-outputs
[INFO] Generating build script...
[INFO] Generating build script completed, took 370ms

[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 11.6s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 998ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Deleting 3 declared outputs which already existed on disk.
[INFO] Checking for unexpected pre-existing outputs. completed, took 5ms

[INFO] Running build...
[INFO] inject_generator:inject_generator on test/widget_test.dart:Generating DI summary for boilerplate|test/widget_test.dart
[INFO] inject_generator:inject_generator on test/widget_test.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/app_theme.dart:Generating DI summary for boilerplate|lib/constants/app_theme.dart
[INFO] inject_generator:inject_generator on lib/constants/app_theme.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/assets.dart:Generating DI summary for boilerplate|lib/constants/assets.dart
[INFO] inject_generator:inject_generator on lib/constants/assets.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/colors.dart:Generating DI summary for boilerplate|lib/constants/colors.dart
[INFO] inject_generator:inject_generator on lib/constants/colors.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/dimens.dart:Generating DI summary for boilerplate|lib/constants/dimens.dart
[INFO] inject_generator:inject_generator on lib/constants/dimens.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/font_family.dart:Generating DI summary for boilerplate|lib/constants/font_family.dart
[INFO] inject_generator:inject_generator on lib/constants/font_family.dart:After resolve
[INFO] inject_generator:inject_generator on lib/constants/strings.dart:Generating DI summary for boilerplate|lib/constants/strings.dart
[INFO] inject_generator:inject_generator on lib/constants/strings.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/local/constants/db_constants.dart:Generating DI summary for boilerplate|lib/data/local/constants/db_constants.dart
[INFO] inject_generator:inject_generator on lib/data/local/constants/db_constants.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/local/datasources/post/post_datasource.dart:Generating DI summary for boilerplate|lib/data/local/datasources/post/post_datasource.dart
[INFO] inject_generator:inject_generator on lib/data/local/datasources/post/post_datasource.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/network/apis/posts/post_api.dart:Generating DI summary for boilerplate|lib/data/network/apis/posts/post_api.dart
[INFO] inject_generator:inject_generator on lib/data/network/apis/posts/post_api.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/network/constants/endpoints.dart:Generating DI summary for boilerplate|lib/data/network/constants/endpoints.dart
[INFO] inject_generator:inject_generator on lib/data/network/constants/endpoints.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/network/dio_client.dart:Generating DI summary for boilerplate|lib/data/network/dio_client.dart
[INFO] inject_generator:inject_generator on lib/data/network/dio_client.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/network/exceptions/network_exceptions.dart:Generating DI summary for boilerplate|lib/data/network/exceptions/network_exceptions.dart
[INFO] inject_generator:inject_generator on lib/data/network/exceptions/network_exceptions.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/network/rest_client.dart:Generating DI summary for boilerplate|lib/data/network/rest_client.dart
[INFO] inject_generator:inject_generator on lib/data/network/rest_client.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/repository.dart:Generating DI summary for boilerplate|lib/data/repository.dart
[INFO] inject_generator:inject_generator on lib/data/repository.dart:After resolve
[INFO] inject_generator:inject_generator on lib/data/sharedpref/constants/preferences.dart:Generating DI summary for boilerplate|lib/data/sharedpref/constants/preferences.dart
[INFO] inject_generator:inject_generator on lib/data/sharedpref/constants/preferences.dart:After resolve
[INFO] Generating SDK summary...
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[INFO] inject_generator:inject_generator on lib/data/sharedpref/shared_preference_helper.dart:Generating DI summary for boilerplate|lib/data/sharedpref/shared_preference_helper.dart
[INFO] inject_generator:inject_generator on lib/data/sharedpref/shared_preference_helper.dart:After resolve
[SEVERE] inject_generator:inject_generator on test/widget_test.dart:

Bad state: Future already completed
[INFO] 2.5s elapsed, 1/17 actions completed.
[INFO] 3.6s elapsed, 1/17 actions completed.
[INFO] 4.6s elapsed, 1/17 actions completed.
[INFO] 5.6s elapsed, 1/17 actions completed.
[INFO] 6.7s elapsed, 1/17 actions completed.
[INFO] 7.8s elapsed, 1/17 actions completed.
[INFO] 8.9s elapsed, 1/17 actions completed.
[INFO] 10.0s elapsed, 1/17 actions completed.
[INFO] 11.0s elapsed, 1/17 actions completed.
[INFO] 12.0s elapsed, 1/17 actions completed.
[INFO] 13.1s elapsed, 1/17 actions completed.
[INFO] 14.2s elapsed, 1/17 actions completed.
[INFO] 15.2s elapsed, 1/17 actions completed.
[INFO] 16.3s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - inject_generator:inject_generator on lib/constants/app_theme.dart
  - inject_generator:inject_generator on lib/constants/assets.dart
  - inject_generator:inject_generator on lib/constants/colors.dart
  - inject_generator:inject_generator on lib/constants/dimens.dart
  - inject_generator:inject_generator on lib/constants/font_family.dart
  .. and 11 more

[INFO] 17.6s elapsed, 1/17 actions completed.
[INFO] 18.7s elapsed, 1/17 actions completed.
[INFO] 19.7s elapsed, 1/17 actions completed.
[INFO] 20.8s elapsed, 1/17 actions completed.
[INFO] 21.9s elapsed, 1/17 actions completed.
[INFO] 23.0s elapsed, 1/17 actions completed.
[INFO] 24.0s elapsed, 1/17 actions completed.
[INFO] 25.0s elapsed, 1/17 actions completed.
[INFO] 26.1s elapsed, 1/17 actions completed.
[INFO] 27.2s elapsed, 1/17 actions completed.
[INFO] 28.2s elapsed, 1/17 actions completed.
[INFO] 29.3s elapsed, 1/17 actions completed.
[INFO] 30.4s elapsed, 1/17 actions completed.
[INFO] 31.4s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.1s, waiting on:
  - inject_generator:inject_generator on lib/constants/app_theme.dart
  - inject_generator:inject_generator on lib/constants/assets.dart
  - inject_generator:inject_generator on lib/constants/colors.dart
  - inject_generator:inject_generator on lib/constants/dimens.dart
  - inject_generator:inject_generator on lib/constants/font_family.dart
  .. and 11 more

[INFO] 32.7s elapsed, 1/17 actions completed.
[INFO] 33.8s elapsed, 1/17 actions completed.
[INFO] 34.9s elapsed, 1/17 actions completed.
[INFO] 36.0s elapsed, 1/17 actions completed.
[INFO] 37.1s elapsed, 1/17 actions completed.
[INFO] 38.1s elapsed, 1/17 actions completed.
[INFO] 39.2s elapsed, 1/17 actions completed.
[INFO] 40.3s elapsed, 1/17 actions completed.
[INFO] 41.4s elapsed, 1/17 actions completed.
[INFO] 42.5s elapsed, 1/17 actions completed.
[INFO] 43.6s elapsed, 1/17 actions completed.
[INFO] 44.7s elapsed, 1/17 actions completed.
[INFO] 45.7s elapsed, 1/17 actions completed.
[WARNING] No actions completed for 15.0s, waiting on:
  - inject_generator:inject_generator on lib/constants/app_theme.dart
  - inject_generator:inject_generator on lib/constants/assets.dart
  - inject_generator:inject_generator on lib/constants/colors.dart
  - inject_generator:inject_generator on lib/constants/dimens.dart
  - inject_generator:inject_generator on lib/constants/font_family.dart
  .. and 11 more

[INFO] 47.7s elapsed, 1/17 actions completed.
[INFO] 48.8s elapsed, 1/17 actions completed.
[INFO] 49.9s elapsed, 1/17 actions completed.
[INFO] 51.0s elapsed, 1/17 actions completed.
[INFO] 52.0s elapsed, 1/17 actions completed.
[INFO] 53.0s elapsed, 1/17 actions completed.
[INFO] 54.1s elapsed, 1/17 actions completed.

**Comment by suryoaji** [comment]
Hi @simsimatoo i also face this issue, pls advise @zubairehman. thanks.

**Comment by radoo11** [comment]
Hello, today I have noticed it's happening also in my project. I downloaded clean **flutter-boilerplate-project** repository and problem still exists. Best regards.

**Comment by radoo11** [comment]
Hi,

I had the same issues. I have solved this problem by:

1. flutter upgrade
2. flutter pub upgrade
3. flutter clean
4. flutter pub get
5. flutter packages pub run build_runner build --delete-conflicting-outputs --verbose

It's worked for me. Best regards.

**Comment by simsimatoo** [comment]
my brother


I want add Arabic language


Language(code: 'AR', locale: 'ar', language: 'Arabic'),

________________________________
من: radoo11 <notifications@github.com>
‏‏تم الإرسال: 21/ذو الحجة/1441 01:54 م
إلى: zubairehman/flutter-boilerplate-project <flutter-boilerplate-project@noreply.github.com>
نسخة: simsimatoo <al.alhamli@hotmail.com>; Mention <mention@noreply.github.com>
‏‏الموضوع: Re: [zubairehman/flutter-boilerplate-project] flutter-boilerplate-project (#68)


Hi,

I had the same issues. I have solved this problem by:

  1.  flutter upgrade
  2.  flutter pub upgrade
  3.  flutter clean
  4.  flutter pub get
  5.  flutter packages pub run build_runner build --delete-conflicting-outputs --verbose

It's worked for me. Best regards.

**Comment by zubairehman** [comment]
@simsimatoo will add support to that.

Will also update all the dependencies and push the updates.

Thanks.

**Comment by suryoaji** [comment]
> Hi,
> 
> I had the same issues. I have solved this problem by:
> 
> 1. flutter upgrade
> 2. flutter pub upgrade
> 3. flutter clean
> 4. flutter pub get
> 5. flutter packages pub run build_runner build --delete-conflicting-outputs --verbose
> 
> It's worked for me. Best regards.

it works seamlessly thanks

**Comment by heycodingkr** [comment]
I had same issus. and I resolved by changing dependency of analyzer version **from analyzer: ^0.39.12  to 0.39.14.** 

Now it works well.

**Comment by HardikKSavaliya** [comment]
AddOns:
if you still facing a build issue then try with Administrator privilege and move `source_gen, analyzer, intl` in dev_dependencies.

**Comment by kadnan0900** [comment]
If any one still facing this issue please follow these steps:
1. Move these dependencies source_gen, analyzer and intl from dependency_overrides: to dev_dependencies: .
2. Run these commands in terminal which are given below:
    flutter upgrade
    flutter pub upgrade
    flutter clean
    flutter pub get
    flutter packages pub run build_runner build --delete-conflicting-outputs --verbose

**Comment by prayatna** [comment]
> If any one still facing this issue please follow these steps:
> 
> 1. Move these dependencies source_gen, analyzer and intl from dependency_overrides: to dev_dependencies: .
> 2. Run these commands in terminal which are given below:
>    flutter upgrade
>    flutter pub upgrade
>    flutter clean
>    flutter pub get
>    flutter packages pub run build_runner build --delete-conflicting-outputs --verbose

Followed this, and have my version as below worked for me.
```
  source_gen: 0.9.6
  analyzer: 0.39.14
  intl: ^0.16.1 
```

**Comment by harrykc** [comment]
Flutter release 1.22.0 stable version, when build project it said "Bad state: Unexpected diagnostics: This requires the 'non-nullable' language feature to be enabled." with infinite loop.

**Comment by roliestiket** [comment]
For anyone that still facing this issue, please make sure your flutter version is v1.xx.xx, because when you run `flutter upgrade` it'll upgraded into flutter v2.0, I've been trying to figuring this out for hours until I realize that I'm using flutter v2.0.

If you need to back to flutter v1.xx.xx you can run this steps :
- `flutter downgrade`
- `flutter doctor`
- `flutter clean`
- Maybe you need to checkout your repo to the original version because the `pubspec.yaml` already changed on your previous attempt.
- `flutter pub get`
- `flutter packages pub run build_runner watch --delete-conflicting-outputs`

I hope this can save your time.

**Comment by roliestiket** [comment]
For anyone that still facing this issue, please make sure your flutter version is v1.xx.xx, because when you run `flutter upgrade` it'll upgrade the flutter into v2.0, I've been trying to figuring this out for hours until I realize that I'm using flutter v2.0.

If you need to back to flutter v1.xx.xx you can run this steps :

- `flutter downgrade`
- `flutter doctor`
- `flutter clean`
- Maybe you need to checkout your repo to the original version because the `pubspec.yaml` already changed on your previous attempt.
- `flutter pub get`
- `flutter packages pub run build_runner watch --delete-conflicting-outputs`

I hope this can save your time.

**Comment by rolies106** [comment]
For anyone that still facing this issue, please make sure your flutter version is v1.xx.xx, because when you run `flutter upgrade` it'll upgrade the flutter into v2.0, I've been trying to figuring this out for hours until I realize that I'm using flutter v2.0.

If you need to back to flutter v1.xx.xx you can run this steps :

- `flutter downgrade`
- `flutter doctor`
- `flutter clean`
- Maybe you need to checkout your repo to the original version because the `pubspec.yaml` already changed on your previous attempt.
- `flutter pub get`
- `flutter packages pub run build_runner watch --delete-conflicting-outputs`

I hope this can save your time.

**Comment by aminazirani** [comment]
Unfortunately I can't get the web version to finish building on none of the available flutter versions and channels. Has anyone been able to get it to run?

**Comment by andj207** [comment]
I still have this issue, the project cannot be built and run infinitely `[INFO] 2.6s elapsed, 1/17 actions completed.`. I am on an Apple M1 device, only this command `flutter packages pub run build_runner watch --delete-conflicting-outputs ` has the issue, other ones from the instruction work well.

**Comment by aminazirani** [comment]
What I did was to downgrade my flutter version and run the builder again. After that I upgraded to the newest flutter version again. Build will still not work but everything else works.

**Comment by andj207** [comment]
@aminazirani Can you share the command and what version you downgraded? Thanks a lot!
