### ISSUE TITLE
The getter 'externalKeyword' isn't defined for the class 'TopLevelVariableDeclaration'

### ISSUE THREAD

**Issue by codemeall** [zubairehman/flutter-boilerplate-project#70]
in running this in mac : `flutter packages pub run build_runner build --delete-conflicting-outputs`

`Failed to precompile build_runner:build_runner:
../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/dart_style-1.3.7/lib/src/source_visitor.dart:2618:21: Error: The getter 'externalKeyword' isn't defined for the class 'TopLevelVariableDeclaration'.
 - 'TopLevelVariableDeclaration' is from 'package:analyzer/dart/ast/ast.dart' ('../../../../Development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.17/lib/dart/ast/ast.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'externalKeyword'.
      modifier(node.externalKeyword);
                    ^^^^^^^^^^^^^^^
pub finished with exit code 1`

anyone here know's the root cause of this? any help or suggestion is appreciated

**Comment by codemeall** [comment]
it got resolved for me when I move 'analyzer' from `dependency_overrides` to `dev_dependencies` in my machine.

**Comment by hienhodeveloper** [comment]
i got the same issue today. still waiting for fixing

**Comment by hienhodeveloper** [comment]
> it got resolved for me when I move 'analyzer' from `dependency_overrides` to `dev_dependencies` in my machine.

Thank you!!!!! I did it

**Comment by mthinyane** [comment]
> it got resolved for me when I move 'analyzer' from `dependency_overrides` to `dev_dependencies` in my machine.

Thanks! This solution works...
