### ISSUE TITLE
Not Pub get Project 

### ISSUE THREAD

**Issue by BhargavSavasani** [zubairehman/flutter-boilerplate-project#72]
Hello

Download your project but when pub get
Getting this Error

The current Dart SDK version is 2.9.2.

Because boilerplate depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.
pub get failed (1; Because boilerplate depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.)

**Comment by cwxorochi** [comment]
@BhargavSavasani I encountered the same problem, then I came across some article, and found out that flutter beta version may compatible with this project, https://flutter.dev/docs/development/tools/sdk/upgrading#switching-flutter-channels

**Comment by menglingyu** [comment]
i also get this error

**Comment by menglingyu** [comment]
![image](https://user-images.githubusercontent.com/19648678/95599775-1b9a7400-0a84-11eb-832c-4fb560b94fcc.png)

overrides analyzer it's  work

**Comment by zubairehman** [comment]
please get latest and try again, do let me know if you are still facing the same issue.
