### ISSUE TITLE
build_runner command generates inject files for all the dart files in project

### ISSUE THREAD

**Issue by codemeall** [zubairehman/flutter-boilerplate-project#73]
the command `flutter packages pub run build_runner build --delete-conflicting-outputs` generates inject files for all the .dart tiles in the project, I am new to flutter and would appreciate if I can get more detail on why it is generating files for all .dart files

**Comment by zubairehman** [comment]
Hi @codemeall,

It was due to `inject_generator` file and the library I was using for DI. I have updated the library to `Injectable` and now its not generating files for all `.dart` files.

Thanks.
