### ISSUE TITLE
Is there any special reason why you not use bloc instead of MobX?

### ISSUE THREAD

**Issue by Smilefounder** [zubairehman/flutter-boilerplate-project#75]
Hi, i love your project template! Great work. As Im a starter in flutter. And there is too many topics between Bloc vs MobX. However, i would love to ask for your advice and your personal opinion.

Best regards.
Huy Nguyen

**Comment by zubairehman** [comment]
Hi,

There are couple of reasons I didn't use Bloc pattern and these are as follows:

- with mobX you need to write less boilerplate coz the code generation will do the job for you.

- easy to understand and debug
- can be used in widgets and model classes
- suitable for large projects

Bloc is also a very good design pattern but as soon as your project grows then it's very hard to maintain and debug streams. Also, the other very important aspect that I see in any state management solution is that how fast I can onboard someone on my project.

Hope this answers your question.

**Comment by Smilefounder** [comment]
thanks a lot.
