### ISSUE TITLE
About Using Provider

### ISSUE THREAD

**Issue by ibrahimdevs** [zubairehman/flutter-boilerplate-project#79]
Hi @zubairehman ,

In project, provider using only for share store instance with sub widgets in tree. (different pages.) Is there any different using scenerio for Provider in this project?

So can we use Get_it instead of provider here? If possible, which one do you prefer and why?

I feel get_it more simpler and because of there is no context requirement, we should use get_it. What is your thoughts?

Thanks,

**Comment by zubairehman** [comment]
Hi @ibrahimdevs,

yes, you can use get_it as I am using the provider just to pass the store to different widgets/screens. If time permits, i will add some examples of get_it in the new branch :)
