### ISSUE TITLE
Your Flutter application is created using an older version of the Android embedding. It's being deprecated in favor of Android embedding v2.

### ISSUE THREAD

**Issue by RayhanYulanda** [zubairehman/flutter-boilerplate-project#80]
Got this warning when i tried to install the packages
```
Warning
──────────────────────────────────────────────────────────────────────────────
Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. Follow the
steps at

https://flutter.dev/go/android-project-migration

to migrate your project.
```

**Comment by Alexakis97** [comment]
How can we fix that?

**Comment by RayhanYulanda** [comment]
> How can we fix that?

We have to upgrade it 😅

**Comment by Alexakis97** [comment]
do you wanna schedule a call? let me know :D we can work on it if you down

**Comment by RayhanYulanda** [comment]
> do you wanna schedule a call? let me know :D we can work on it if you down [here](https://www.linkedin.com/in/philippos-a-a46806177/)

I have finished upgrade the project but i'm not really sure should make PRs it or not because there is some package i've upgrade @Alexakis97

**Comment by Alexakis97** [comment]
Well I really want to make the packages work :'/ and I don't really know how, If you could help out I would appreciate it!

**Comment by zubairehman** [comment]
apologies for the delay, i will update soon :)

**Comment by zubairehman** [comment]
The project has been migrated to v2, please get latest and let me know if there is any issue :)
