### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by elmurphy** [zubairehman/flutter-boilerplate-project#81]
I try to download boilerplate and run it but I got that error on run.
`
[flutter_boilerplate] flutter pub get
Running "flutter pub get" in flutter_boilerplate...             
Because boilerplate depends on flutter_localizations any from sdk which depends on intl 0.17.0-nullsafety.2, intl 0.17.0-nullsafety.2 is required.

So, because boilerplate depends on intl ^0.16.1, version solving failed.
pub get failed (1; So, because boilerplate depends on intl ^0.16.1, version solving failed.)
exit code 1
`

**Comment by thegumza** [comment]
I have sam error becase I use flutter in beta chanel.
Check your channel by
flutter channel
if you in beta try to change to stable channel by
flutter channel stable
flutter upgrade
Now I try to use stable chanel it's work.

**Comment by elmurphy** [comment]
You are right, that's fix my problem. Noted here for others.

**Comment by allanlaal** [comment]
issue still persists in **Flutter 2.0 stable** with flutter-boilerplate-project master tip:

`$ flutter pub get
Because boilerplate depends on flutter_localizations any from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
So, because boilerplate depends on intl ^0.16.1, version solving failed.`

**Comment by uvios** [comment]
@allanlaal I am facing same issue as well

**Comment by allanlaal** [comment]
@uvios my current dirty fix is to append this to pubspec.yaml:

dependency_overrides:
  intl: ^0.16.1
  path: ^1.7.0

**Comment by uvios** [comment]
please remove f_logs dependency and change   intl: ^0.16.1 ==>  intl: ^0.17.0. this worked for me

**Comment by allanlaal** [comment]
> please remove f_logs dependency and change intl: ^0.16.1 ==> intl: ^0.17.0. this worked for me

still produces error:
`pub get failed (1; Because boilerplate depends on intl ^1.7.0 which doesn't match any versions, version solving
failed.)`
