### ISSUE TITLE
How to inject a repository to a store(which is not created in main.dart) ?

### ISSUE THREAD

**Issue by blackkara** [zubairehman/flutter-boilerplate-project#84]
You just injected the `repository` to `ThemeStore` and `LanguageStore` in main.dart, thats okay.

So what about the `FormStore` ? As the title says, how to inject the `repository` ?

**Comment by zubairehman** [comment]
Hi @blackkara,

In my case, `FormStore` doesn't need a repository but still if you have a case where you want to pass the repository then have a look at the code below:

```
FormStore _formStore = FormStore(getIt<Repository>());
```

**or**

```
  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    _formStore = = FormStore(getIt<Repository>());
  }
```

Thanks.
