### ISSUE TITLE
Update to null safety

### ISSUE THREAD

**Issue by beingentangled** [zubairehman/flutter-boilerplate-project#86]

**Comment by selmaskopljakovic** [comment]
+1 for updating to null safety.

**Comment by beingentangled** [comment]
@zubairehman for updating to null safety,  we need to migrate to a different item for DI other than inject package from google right?

**Comment by selmaskopljakovic** [comment]
Hi,
I have issues with dependency injection generating files. Seems like 
inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator
      ref: 7c3cbf6
      
and inject are too old. 
I updated all packages to the newest. Everything else works fine but generating files.
Can you please do an update on this?

**Comment by beingentangled** [comment]
Yeah, that was the main problem! @zubairehman is working on it. might be changing to new DI libs. @zubairehman if you could say which library you're considering integrating that would be too helpful.

**Comment by zubairehman** [comment]
Hi @ALL,

I have updated the DI library for this boilerplate template, please go through the feature/null-safety branch for more details. Feel free to reach out to me if you find any issues.

Note: I will merge the changes into master as soon as I am done testing and implementing other features.

Thanks.
