### ISSUE TITLE
Migrate this boilerplate project to flutter v2

### ISSUE THREAD

**Issue by volethanh** [zubairehman/flutter-boilerplate-project#87]
Hi,

I am just wondering if this boilerplate project is planed to migrate to flutter 2.x ?

Thanks in advance

**Comment by zubairehman** [comment]
Hi @all,

I have updated the DI library for this boilerplate template, please go through **[feature/null-safety](https://github.com/zubairehman/flutter-boilerplate-project/tree/feature/null-safety)** branch for more details. Feel free to reach out to me if you find any issues.

Note: I will merge the changes into master as soon as I am done testing and implementing other features.

Thanks.
