### ISSUE TITLE
Infinite loop issue continues

### ISSUE THREAD

**Issue by MuhammadSufyanMalik** [zubairehman/flutter-boilerplate-project#89]
pubspec.yaml file

name: boilerplate
description: A flutter boilerplate project created using MobX and Provider.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

 The following adds the Cupertino Icons font to your application.
  Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  // The following adds the shared pref as a dependency in your application
  shared_preferences: ^0.5.10

  // A composable, Future-based library for making HTTP requests.
  http: ^0.12.2

// Flogs, a powerful logging framework
  // f_logs: ^1.2.2 #I commented this because it is not version failed issue.

  // MobX is a library for reactively managing the state of your applications. Use the power of
  // observables, actions, and reactions to supercharge your Dart and Flutter apps.
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2

  // An helper to easily exposes a value using InheritedWidget without having to write one.
  provider: ^4.3.2+1

  // String validation and sanitization for Dart. Dart 2-compatible version of validator
  validators: ^2.0.1

  //A powerful Http client for Dart
  dio: 3.0.10

 // A flexible widget for user notification. Customize your text, button, duration, animations
  and much more. For Android devs, it is made to replace Snackbars and Toasts.
  flushbar: ^1.10.4

  // Material Dialog
  material_dialog: ^0.0.9

 // This package provides internationalization and localization facilities, including message
 // translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  #intl: ^0.17.0

  //Dependency injection
  inject:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject
      ref: 7c3cbf6

dev_dependencies:
  flutter_test:
    sdk: flutter

  // The following adds the launcher icon support to your application.
  //run below mentioned commands to generate launcher icons
  // flutter packages get
  // flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.5
  mobx_codegen: ^1.1.0+1
  json_serializable: ^3.4.1
  build_runner: ^1.10.2
  source_gen: 0.9.6
  analyzer: ^0.39.15
  intl: ^0.17.0
  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator
      ref: 7c3cbf6

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true

// For information on the generic Dart art of this file, see the
// following page: https://www.dartlang.org/tools/pub/pubspec

// The following section is specific to Flutter.
flutter:

  // The following line ensures that the Material Icons font is
  // included with your application, so that you can use the icons in
  // the material Icons class.
  uses-material-design: true

  // To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/icons/
  - assets/lang/

  // An image asset can refer to one or more resolution-specific "variants", see
  // https://flutter.io/assets-and-images/#resolution-aware.

  // For details regarding adding assets from package dependencies, see
  // https://flutter.io/assets-and-images/#from-packages

  // To add custom fonts to your application, add a fonts section here,
  // in this "flutter" section. Each entry in this list should have a
  //"family" key with the font family name, and a "fonts" key with a
  // list giving the asset and other descriptors for the font. For
  // example:
  fonts:
  - family: ProductSans
    fonts:
    - asset: assets/fonts/Product-Sans-Regular.ttf
    - asset: assets/fonts/Product-Sans-Italic.ttf
      style: italic
    - asset: assets/fonts/Product-Sans-Bold.ttf
      weight: 700

 For details regarding fonts from package dependencies,
  see https://flutter.io/custom-fonts/#from-packages

Flutter Version

Flutter 2.0.3 
Framework • revision 4d7946a68d (5 days ago) • 2021-03-18 17:24:33 -0700
Engine • revision 3459eb2436
Tools • Dart 2.12.2
..
Kindly help, if anyone solves this issue.
Thanks

**Comment by andj207** [comment]
I have this infinite loop too and cannot get it to work.

**Comment by gc-robotics** [comment]
Same. Upgrade analyzer as advised on one of the closed issues doesnt help.

**Comment by zubairehman** [comment]
Hi @all,

I have updated the DI library for this boilerplate template, please go through **[feature/null-safety](https://github.com/zubairehman/flutter-boilerplate-project/tree/feature/null-safety)** branch for more details. Feel free to reach out to me if you find any issues.

Note: I will merge the changes into master as soon as I am done testing and implementing other features.

Thanks.
