### ISSUE TITLE
Please update to flutter 2

### ISSUE THREAD

**Issue by anwarulislam** [zubairehman/flutter-boilerplate-project#91]
I tried to update the boilerplate to flutter 2. But, got stuck with some packages. Can you please update it to flutter 2?

**Comment by prathameshm009** [comment]
Facing the same issue, this template in not compatible with Flutter 2, please help!

**Comment by anwarulislam** [comment]
Hey @prathameshm009 
I had a conversation with @zubairehman Brother. He is working on the update, he said. Please keep patience

**Comment by zubairehman** [comment]
Hi @all,

I have updated the DI library for this boilerplate template, please go through **[feature/null-safety](https://github.com/zubairehman/flutter-boilerplate-project/tree/feature/null-safety)** branch for more details. Feel free to reach out to me if you find any issues.

Note: I will merge the changes into master as soon as I am done testing and implementing other features.

Thanks.

**Comment by anwarulislam** [comment]
Thanks for the update

**Comment by anwarulislam** [comment]
Hello, @Zubair Rehman ***@***.***> Bhaiya,

Should I upgrade all packages to the latest version?

Warmest regards,
Anwarul Islam
Tech Associate | 10 Minute School
Mobile: +8801815651830
E-mail: ***@***.***
www.10minuteschool.com

[image: facebook] <https://www.facebook.com/anwaarul.islaam/> [image:
linkedin] <https://www.linkedin.com/in/anwaarulislaam>
