### ISSUE TITLE
Dart Inject vs Injector

### ISSUE THREAD

**Issue by gc-robotics** [zubairehman/flutter-boilerplate-project#92]
Google's Inject repo has been archived. 
It's been in preview for the past 3 years and there is no active support or bug fixing. 

Looking at alternatives, I have come across Injector. 
Any thought on that?

**Comment by anwarulislam** [comment]
Hello @gc-robotics, I saw the same thing on google's repo. It should be replaced by a better one. Can you please update all the dependencies to the latest version with solving that issue by replacing `inject.dart` with the best one?

Then please fork the repository for your account and upload all the updates. It will be a very helpful thought. I'm so new that I cannot figure out what's going on in this project.

**Comment by zubairehman** [comment]
Hi,

Currently, we have been in a process of migrating inject to flutter 2.0 to make it work with our boilerplate. We will also push a new branch with an alternative DI.

Thanks.

**Comment by gc-robotics** [comment]
Hi @zubairehman ,
Could you please share the url to the inject-related work as the Google one has been archived. 
Could you also share what's the progress status at the moment? 
Thanks,
GC

**Comment by gc-robotics** [comment]
Hi @zubairehman ,

I have spotted this repo: https://github.com/zubairehman/inject.dart/tree/develop
Checked also the original/forked one. It seems that the ugrade to 2 has been completed. 
Am I wrong? have you tried it? 

Thanks.

**Comment by zubairehman** [comment]
Hi @all,

I have updated the DI library for this boilerplate template, please go through **[feature/null-safety](https://github.com/zubairehman/flutter-boilerplate-project/tree/feature/null-safety)** branch for more details. Feel free to reach out to me if you find any issues.

Note: I will merge the changes into master as soon as I am done testing and implementing other features.

Thanks.
