### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by AzarouAmine** [zubairehman/flutter-boilerplate-project#95]
Is there any possible way for this boilerplate to be migrated to null safety? I've tried doing so myself, but it seems inject_geenrator and inject packages are keeping the migration tool from finishing.

**Comment by masreplay** [comment]
yes please!

**Comment by zubairehman** [comment]
Hi @ALL,

I have updated the DI library for this boilerplate template, please go through **feature/null-safety** branch for more details. Feel free to reach out to me if you find any issues.

Note: I will merge the changes into master as soon as I am done testing and implementing other features.

Thanks
