### ISSUE TITLE
migrate to null safety and flutter 2 

### ISSUE THREAD

**Issue by masreplay** [zubairehman/flutter-boilerplate-project#96]
a lot of package work on flutter 2 so please we need a migration and the time of it

**Comment by zubairehman** [comment]
Hi,

I have updated the DI library for this boilerplate template, please go through **feature/null-safety** branch for more details. Feel free to reach out to me if you find any issues.

Note: I will merge the changes into master as soon as I am done testing and implementing other features.

Thanks
